name: Continuous Delivery

on:
    push:
        tags: ['v*']

jobs:
    create_release_notes:
        runs-on: ubuntu-latest
        steps:
            - name: Create Release Notes
              id: create_release_notes
              uses: release-drafter/release-drafter@v5
              with:
                  publish: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
            release_upload_url: ${{ steps.create_release_notes.outputs.upload_url }}

    build:
        runs-on: windows-latest
        needs:
            - create_release_notes

        steps:
            - name: Clone
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.100

            - name: Configure Visual Studio
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Nerdbank.GitVersioning
              uses: dotnet/nbgv@master
              id: nbgv
              with:
                  setAllVars: true

            - name: Build
              working-directory: ./src/Microsoft.ApplicationModel.Resources/projection
              run: |
                & MSBuild.exe /nologo /restore /bl /m /p:Configuration=Release `
                  /p:ContinuousIntegrationBuild=true `
                  /t:Pack

            - name: Prepare Assets for Upload
              working-directory: ./src/Microsoft.ApplicationModel.Resources/projection/bin/Release
              run: |
                $packages = (dir *.symbols.nupkg)
                if ($packages.Length -ne 0) {
                  mv $packages[0].FullName Sunburst.MRTCore.${{ steps.update_version.outputs.version }}.nupkg -Verbose
                } else {
                  Write-Error "Could not find any package files"
                }

            - name: Upload Package
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.create_release_notes.outputs.release_upload_url }}
                  asset_path: ./src/Microsoft.ApplicationModel.Resources/projection/bin/Release/Sunburst.MRTCore.${{ steps.update_version.outputs.version }}.nupkg
                  asset_name: Sunburst.MRTCore.${{ steps.update_version.outputs.version }}.nupkg
                  asset_content_type: application/zip
