name: Build Release

on:
    push:
        tags: ['v*']

jobs:
    create_release_notes:
        runs-on: ubuntu-latest
        steps:
            - name: Create Release Notes
              id: create_release_notes
              uses: release-drafter/release-drafter@v5
              with:
                  publish: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
            name: ${{ steps.create_release_notes.outputs.name }}

    build:
        runs-on: windows-latest
        needs:
            - create_release_notes

        steps:
            - name: Clone
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.100

            - name: Configure Visual Studio
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Nerdbank.GitVersioning
              uses: dotnet/nbgv@master
              id: nbgv
              with:
                  setAllVars: true

            - name: Build
              working-directory: ./src/Microsoft.ApplicationModel.Resources/projection
              run: |
                & MSBuild.exe /nologo /restore /bl /m /p:Configuration=Release /t:Pack

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_REPOSITORY: SunburstApps/MRTCore
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: ${{ needs.create_release_notes.outputs.name }}
                  files: src/Microsoft.ApplicationModel.Resources/projection/bin/Release/*.nupkg
                  fail_on_unmatched_files: true
                  draft: true
