name: Test PR Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Clone
    - uses: actions/setup-dotnet@v1
      name: Install .NET Core
      with:
        dotnet-version: 5.0.100
    - uses: microsoft/setup-msbuild@v1.0.2
      name: Configure Visual Studio
    - name: Build
      working-directory: ./src/Microsoft.ApplicationModel.Resources/projection
      run: |
        & MSBuild.exe /nologo /m /p:Configuration=Release /t:Pack
    - uses: github/upload-artifact@v2
      name: Upload Assets
      with:
        name: nuget
        path: src/Microsoft.ApplicationModel.Resources/projection/bin/Release/*.nupkg
        if-no-files-found: error
